# -*- coding: utf-8 -*-
"""9 sep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t5gT7lBbPcY90Omxc9jmr-QD4WExRrzv
"""



import pandas as pd

df = pd.read_csv('/content/USD_INR Historical Data.csv')
display(df.head())

df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')
df = df.set_index('Date').sort_index()
df = df.dropna(subset=['Price']) # Drop rows where 'Price' is missing

display(df.head())
display(df.info())

# Drop the 'Vol.' column as it has no data
df = df.drop(columns=['Vol.'])

# Create lagged feature for the previous day's price
df['Price_lag_1'] = df['Price'].shift(1)

df = df.dropna() # Drop rows with NaN values created by shifting

display(df.head())